# Generated by Django 5.2.1 on 2025-05-20 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0001_initial'),
    ]

    operations = [
    ]
