# Generated by Django 5.2.1 on 2025-05-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flota', '0002_alter_mantenimientocorrectivo_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimientocorrectivo',
            name='estado',
            field=models.CharField(choices=[('reportado', 'Reportado'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='reportado', max_length=10),
        ),
        migrations.AlterField(
            model_name='mantenimientocorrectivo',
            name='prioridad',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=5),
        ),
        migrations.AlterField(
            model_name='mantenimientopreventivo',
            name='estado',
            field=models.CharField(choices=[('reportado', 'Reportado'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=10),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('en_mantenimiento', 'En Mantenimiento'), ('desincorporado', 'Desincorporado')], default='activo', max_length=17),
        ),
    ]
